# PHY 604: Homework #3 Solutions

In [5]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<div style="background-color: powderblue; color: black; padding: 10px;">
1. _Periodic tridiagonal_. In class, we saw how to write a
 Gaussian elimination routine for a tridiagonal matrix.  Here we
 build on that, with one little twist.  Consider the system below:
 \begin{equation}
   \left ( \begin{array}{ccccccc}
     b_0    & c_0 &        &        &        &        & a_0 \\
     a_1    & b_1 & c_1    &        &        &  \\
            & a_2 & b_2    & c_2  \\
            &     & \ddots & \ddots & \ddots \\
            &     &        & \ddots & \ddots & \ddots \\
            &     &        &        & a_{N-1}& b_{N-1}& c_{N-1} \\
     c_{N}  &     &        &        &        & a_{N}& b_{N} \\
  \end{array}\right )
   \left ( \begin{array}{c}
     x_0 \\ x_1 \\ x_2 \\ \vdots \\ \vdots \\ x_{N-1} \\ x_{N} 
   \end{array} \right )
   =
   \left ( \begin{array}{c}
     d_0 \\ d_1 \\ d_2 \\ \vdots \\ \vdots \\ d_{N-1} \\ d_{N} 
   \end{array} \right )
 \end{equation} 
 Now there are two additional elements, in the far corners.  Also note
 that as written, this is an $N+1 \times N+1$ matrix.  This type
 of matrix arises when you enforce periodic boundary conditions on a
 system (for example, if we had done so in the cubic splines instead
 of the natural boundary conditions).

 <p>We can solve this type of linear system efficiently using a method
 called the Thomas algorithm.  First we eliminate the last row and
 last column.  This gives an $N\times N$ system of the form:
 \begin{equation}
   \underbrace{
   \left ( \begin{array}{ccccccc}
     b_0    & c_0 &        &        &        &        & \\
     a_1    & b_1 & c_1    &        &        &  \\
            & a_2 & b_2    & c_2  \\
            &     & \ddots & \ddots & \ddots \\
            &     &        & \ddots & \ddots & \ddots \\
            &     &        &        & a_{N-2}& b_{N-2}& c_{N-2} \\
            &     &        &        &        & a_{N-1}& b_{N-1} \\
  \end{array}\right )}_{\equiv A^c}
  \underbrace{
   \left ( \begin{array}{c}
     x_0 \\ x_1 \\ x_2 \\ \vdots \\ \vdots \\ x_{N-2} \\ x_{N-1} 
   \end{array} \right )}_{\equiv \tilde{x}}
   =
   \underbrace{
   \left ( \begin{array}{c}
     d_0 \\ d_1 \\ d_2 \\ \vdots \\ \vdots \\ d_{N-2}\\ d_{N-1}  
   \end{array} \right )}_{\equiv \tilde{d}} +
   \underbrace{
   \left ( \begin{array}{c}
     -a_0 \\ 0 \\ 0 \\ \vdots \\ \vdots \\ 0\\ -c_{N-1}  
   \end{array} \right )}_{\equiv \tilde{\eta}} x_N
 \end{equation} 
 Here $\eta$ arises from looking at which terms in the first $N$ rows
 of the original matrix involve the $x_N$ element in the solution vector
 that we are cutting out.  Note that the $\eta$ vector multiplies $x_N$.

 <p>This system is linear, so we can imagine a solution of the form:
 \begin{equation}
   \tilde{x} = x^{(\alpha)} + x^{(\beta)} x_N
 \end{equation}
 
 <p>Substituting this into our new linear system, we see:
 \begin{equation}
   A^c \tilde{x} = A^c x^{(\alpha)} + A^c x^{(\beta)} x_N = \tilde{d} + \eta x_N
 \end{equation}

 <p>This means that we can solve 
 $$A^c x^{(\alpha)} = \tilde{d}$$
 $$A^c x^{(\beta)} = \eta$$
 to get $x^{(\alpha)}$ and $x^{(\beta)}$.  
</div>

 <div style="background-color: powderblue; color: black; padding: 10px;">
 (a) With $x^{(\alpha)}$ and $x^{(\beta)}$ found, we can find $x_N$ by looking
   at the last row of our original system:
   \begin{equation}
     c_N x_0 + a_N x_{N-1} + b_N x_N = d_N
   \end{equation}
   Substitute in the definition of $x_0$ and $x_{N-1}$ from our vector $\tilde{x}$
   and show that 
   \begin{equation}
     x_N = \frac{d_N - c_N x_0^{(\alpha)} - a_N x_{N-1}^{(\alpha)}}{c_N x_0^{(\beta)} + a_N x_{N-1}^{(\beta)} + b_N}
   \end{equation}
</div>

The last row of the original system is:
\begin{equation}
c_N x_0 + a_N x_{N-1} + b_N x_N = d_N
\end{equation}

Substituting our defintion of $\tilde{x}$, we have:
\begin{equation}
c_N (x_0^{(\alpha)} + x_0^{(\beta)} x_N ) + a_N (x_{N-1}^{(\alpha)} + x_{N-1}^{(\beta)} x_N) b_N x_N = d_N
\end{equation}

Solving for $x_N$, we have:
\begin{equation}
x_N (c_N x_0^{(\beta)} + a_N x_{N-1}^{(\beta)} + b_N) = d_N - c_N x_0^{(\alpha)} - a_N x_{N-1}^{(\alpha)}
\end{equation}
giving us:
\begin{equation}
x_N = \frac{d_N - c_N x_0^{(\alpha)} - a_N x_{N-1}^{(\alpha)}}{c_N x_0^{(\beta)} + a_N x_{N-1}^{(\beta)} + b_N}
\end{equation}

<div style="background-color: powderblue; color: black; padding: 10px;">
(b) We can now get the remaining values of $x$ as $\tilde{x} = x^{(\alpha)} + x^{(\beta)} x_N$.

<p>Write a code to solve this periodic tridiagonal system.  Test it by
   writing a corresponding matrix-vector multiply code and find the
   solution for a matrix of the form $b_i = 4$ and $a_i = c_i = 1$ for
   $i = 0, \ldots N$.

</div>

First, here's a function that does the periodic tridiagonal solve -- we take 4 vectors: the 3 diagonals and the RHS, and return the solution.  This routine makes use of the standard tridiagonal solver (below) that we discussed in class.

In [1]:
def tridiag_periodic(a, b, c, d):
    """ Solve the periodic tridiagonal system of the form:

     / b_0  c_0             a_0 \
     | a_1  b_1  c_1             |
     |      a_2  b_2  c_2        |
     |         .    .    .       |
     |            .    .    .    |
     |               .    .      |
     \ c_N            a_N    b_N /

    we do this via the Thomas algorithm
    """

    # we'll consider the matrix to be (N+1) x (N+1) elements
    # and we'll break it into an NxN and extra
    N = len(a)-1

    if not len(a) == len(b) == len(c) == len(d):
        raise ValueError("all inputs should be of the same length")

    # our solution
    x = np.zeros_like(a)

    # consider the sub-matrix that eliminates the last row and column
    ac = a[0:N]
    bc = b[0:N]
    cc = c[0:N]
    dc = d[0:N]

    # we will express the solution as x = xa + xb*xn, where xn is the
    # last component in the solution vector

    xa = np.zeros((N), dtype=np.float64)
    xb = np.zeros((N), dtype=np.float64)

    # solve Ac xa = dc
    xa = tridiag(ac, bc, cc, dc)

    # the second solution uses information from the column we cut
    # out
    eta = np.zeros_like(xa)
    eta[0] = -ac[0]
    eta[N-1] = -cc[N-1]

    # solve Ac xb = eta
    xb = tridiag(ac, bc, cc, eta)

    # now we can compute xn
    x[N] = (d[N] - c[N]*xa[0] - a[N]*xa[N-1])/(c[N]*xb[0] + a[N]*xb[N-1] + b[N])

    # now the remaining solutions
    x[0:N] = xa + xb*x[N]

    return x

Here's the standard tridiagonal solver from class.  It takes the same arguments and returns the solution.  This does not assume periodicity.

In [2]:
def tridiag(a, b, c, d):
    """This is the normal (non-periodic) solver.

    solve the linear system Ax = d where A has the form:

      a_i x_{i-1} + b_i x_i + c_i x_{i+1} = d_i

    for i = 0, n-1 with a_0 = 0 and c_{n-1} = 0

    In matrix form, b is the main diagonal, a is the subdiagonal and c
    is the superdiagonal.

    """

    N = len(a)
    if not len(b) == len(c) == len(d) == N:
        print("ERROR: vectors not the right size")
        return None

    # forward elimination
    cprime = np.zeros((N), dtype=a.dtype)
    dprime = np.zeros((N), dtype=a.dtype)

    cprime[0] = c[0]/b[0]
    dprime[0] = d[0]/b[0]

    for i in range(1, N-1):
        cprime[i] = c[i]/(b[i] - cprime[i-1]*a[i])
        dprime[i] = (d[i] - dprime[i-1]*a[i])/(b[i] - cprime[i-1]*a[i])

    dprime[N-1] = (d[N-1] - dprime[N-2]*a[N-1])/(b[N-1] - cprime[N-2]*a[N-1])

    # back substitution
    x = np.zeros((N), dtype=a.dtype)

    x[N-1] = dprime[N-1]
    for i in reversed(range(0, N-1)):
        x[i] = dprime[i] - cprime[i]*x[i+1]

    return x

To test it all out, here's a function that takes a periodic tridiagonal matrix and multiplies it by a vector x:

In [3]:
def tridiag_periodic_Ax(a, b, c, x):
    """ multiply the tridiagonal matrix A by vector x and return the
        product vector d """

    N = len(a)
    if not len(b) == len(c) == len(x) == N:
        print("ERROR: vectors not the right size")
        return None

    d = np.zeros((N), dtype=a.dtype)

    d[0] = b[0]*x[0] + c[0]*x[1] + a[0]*x[N-1]
    for i in range(1, N-1):
        d[i] = a[i]*x[i-1] + b[i]*x[i] + c[i]*x[i+1]

    d[N-1] = a[N-1]*x[N-2] + b[N-1]*x[N-1] + c[N-1]*x[0]

    return d

In [7]:
N = 20
a = np.zeros(N, dtype=np.float64)
b = np.zeros(N, dtype=np.float64)
c = np.zeros(N, dtype=np.float64)
d = np.zeros(N, dtype=np.float64)
x = np.zeros(N, dtype=np.float64)

# this is the form that the problem specified
a[:] = 1.0
b[:] = 4.0
c[:] = 1.0

# we'll start by picking the solution, then use our matrix multiplication
# routine to compute the RHS corresponding to this solution
x[:] = np.arange(N)

d = tridiag_periodic_Ax(a, b, c, x)
print(x)

# now we'll try to recover the solution by using our periodic tridiagonal
# solver
xnew = tridiag_periodic(a, b, c, d)

print(xnew)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.]


<div style="background-color: powderblue; color: black; padding: 10px;">
2. _Matrix inverse_ (based on Garcia) An iterative method for
  constructing the matrix inverse can be found via Newton's method.  A
  single step in the iteration appears as:
  \begin{equation}
    {\bf X}^{(k+1)} = 2 {\bf X}^{(k)} - {\bf X}^{(k)} {\bf A} {\bf X}^{(k)}
  \end{equation}
  where ${\bf A}$ is the matrix whose inverse we seek and ${\bf X}^{(k)}$ is
  our current guess for the inverse.

 <p> Find the inverse of the following matrix using this technique:
  \begin{equation}
  {\bf A} = \left ( \begin{array}{cccc}
     4 &  3 & 4 & 10 \\ 
     2 & -7 & 3 &  0 \\ 
    -2 & 11 & 1 &  3 \\
     3 & -4 & 0 &  2
   \end{array} \right )
  \end{equation}

  <p>You will need to supply an initial guess and a desired tolerance.
  Be careful with your initial guess---some choices will diverge.
  Think about the operations that are taking place in the first
  iteration to help you devise a good initial guess for ${\bf
    A}^{-1}$.  It will probably help to put some prints in there (or
  work out a $2\times 2$ case analytically).
</div>

The main difficulty here is picking a suitable guess for the inverse.  The paper sent around via e-mail suggested something of the form:
$${\bf X}^{(0)} = \alpha {\bf A}^\intercal$$
where $\alpha$ is a small positive number.  We'll use the maximum element squared.

In [8]:
tol = 1.e-12

def iter_inverse(A, Ainv0):
    """ here A is the matrix and Ainv0 is an initial guess to the
        inverse """

    Ainv = Ainv0.copy()

    err = 1.e10

    iter = 0
    while err > tol:
        Ainv_new = 2.0*Ainv - np.dot(Ainv, np.dot(A, Ainv))

        err = np.max(np.abs(Ainv - Ainv_new))

        Ainv = Ainv_new.copy()

        iter += 1


    print("number of iterations = ", iter)

    return Ainv

In [11]:
A = np.array([ [ 4,  3, 4, 10],
               [ 2, -7, 3,  0],
               [-2, 11, 1,  3],
               [ 3, -4, 0,  2] ], dtype=np.float64)
A

array([[  4.,   3.,   4.,  10.],
       [  2.,  -7.,   3.,   0.],
       [ -2.,  11.,   1.,   3.],
       [  3.,  -4.,   0.,   2.]])

In [12]:
Aguess = np.transpose(A)/np.max(np.abs(A))**2
Aguess

array([[ 0.03305785,  0.01652893, -0.01652893,  0.02479339],
       [ 0.02479339, -0.05785124,  0.09090909, -0.03305785],
       [ 0.03305785,  0.02479339,  0.00826446,  0.        ],
       [ 0.08264463,  0.        ,  0.02479339,  0.01652893]])

In [13]:
Ainv = iter_inverse(A, Aguess)
Ainv

number of iterations =  16


array([[-0.59487179,  0.46153846,  0.99487179,  1.48205128],
       [-0.22051282,  0.15384615,  0.42051282,  0.47179487],
       [-0.11794872,  0.38461538,  0.31794872,  0.11282051],
       [ 0.45128205, -0.38461538, -0.65128205, -0.77948718]])

In [15]:
print(Ainv @ A)

[[  1.00000000e+00   3.55271368e-15   5.55111512e-16  -8.88178420e-16]
 [ -6.66133815e-16   1.00000000e+00   3.88578059e-16  -1.11022302e-16]
 [ -6.10622664e-16   8.88178420e-16   1.00000000e+00  -2.22044605e-16]
 [  8.88178420e-16  -2.22044605e-15  -3.33066907e-16   1.00000000e+00]]


We see that this is close to the identity matrix, with the off-diagonal elements basically machine epsilon.